### ISSUE TITLE
GKE --- Faild toFetch message ---critical

### ISSUE THREAD

**Issue by knidhin1** [GoogleCloudPlatform/mllp#10]
After rolling update of container image with latest tag, GKE mllp conteainer cant complete the process -- no cloud pubsub notification 

W0227 02:40:29.220849       1 handler.go:76] Error fetching message projects/XXXX/locations/us-central1/datasets/XXX/hl7V2Stores/XXXX/messages/XXXX: failed to fetch message: <nil>
I0227 02:40:47.346644       1 healthapiclient.go:190] Sending message of size 2145.
I0227 02:40:47.465420       1 healthapiclient.go:223] Message was successfully sent.

**Comment by raycaig** [comment]
We have updated MLLP adapter to log the error response, you should be able to see why it failed to fetch message now. Could you redeploy the latest MLLP adapter image to GKE and check the error message? I am closing this issue for now but please feel free to re-open it if you are still encountering the issue. Thanks!
