### ISSUE TITLE
Why PubSub subscription?

### ISSUE THREAD

**Issue by pauldraper** [GoogleCloudPlatform/mllp#17]
> The MLLP adapter receives HL7v2 messages via MLLP/TCP, and forwards messages received to Cloud HL7v2 API

How is PubSub is related to any of this?

**Comment by paulchurch** [comment]
Sorry for the confusion, this doc doesn't really capture the big picture.

PubSub is not involved in the inbound path where a message comes in over MLLP and is forwarded to the Healthcare API.

It is used for the outbound path where you can (optionally):
1. Use the notificationConfigs field to configure an HL7v2 store to send notifications to a PubSub topic when messages are created/ingested matching some filter criteria.
2. Configure the MLLP adapter to listen to that PubSub topic.
The adapter will then send those messages matching the criteria out over the external interface.

**Comment by pauldraper** [comment]
Ah thanks for the clarification.
