### ISSUE TITLE
INVALID_ARGUMENT when testing mllp on GKE

### ISSUE THREAD

**Issue by damianesteban** [GoogleCloudPlatform/mllp#2]
We have been testing out the Google Healthcare API specifically with HL7 and as I've run through the tutorials I've hit a roadblock. I should mention that I have a fair bit of experience with Kubernetes and AWS, but not so much Google Cloud.

This step here is what is giving me trouble:

https://cloud.google.com/healthcare/docs/how-tos/mllp-adapter#creating_a_compute_engine_vm_and_sending_messages

When I attempt to send the message from the VM I do not see a response, and the logs in the pod show me the following error:

    I0411 17:27:33.756432       1 healthapiclient.go:163] Dialing connection to https://healthcare.googleapis.com:443/v1beta1
    I0411 17:27:58.809932       1 mllpreceiver.go:107] Accepted connection from 10.128.0.5:58698
    I0411 17:27:58.810140       1 healthapiclient.go:182] Sending message of size 319.
    E0411 17:27:58.880369       1 mllpreceiver.go:118] handleMessage: Send: request failed: 400
    {
      "error": {
        "code": 400,
        "message": "location ID invalid, expected us-central1",
        "status": "INVALID_ARGUMENT"
      }
    }
    I0411 17:27:58.880691       1 mllpreceiver.go:119] Closed connection from 10.128.0.5:58698

This error is perplexing because the GKE cluster and the VM are in the same region/zone. Is this an issue with PubSub or the mllp adapter?

Thanks

**Comment by lastomato** [comment]
Hi Damian, it looks like there is something wrong with the HL7v2 store endpoint. Could you share what you set as hl7_v2_location_id in your MLLP adapter deployment config?

**Comment by damianesteban** [comment]
I thought this might be the issue. When I tried assigning the sets/stores with the full path names I had another config issue. Here it is:

```
            - "--hl7_v2_project_id=healthcare-api-dev"
            - "--hl7_v2_location_id=us-central1-b"
            - "--hl7_v2_dataset_id=bpt-test-set"
            - "--hl7_v2_store_id=hlstore"
```

**Comment by lastomato** [comment]
Can you try us-central1 instead of us-central1-b? location id is more like a zone id instead of region id. We'll try to make that clear in the docs.

**Comment by damianesteban** [comment]
That did the trick! Thank you.

**Comment by lastomato** [comment]
Great to hear that it works for you.
