### ISSUE TITLE
Authorization Error on Run

### ISSUE THREAD

**Issue by cunninghamb505** [GoogleCloudPlatform/mllp#20]
When testing locally the docker image for MLLP HL7 I get a could not find default credentials. I tried both windows and Linux with same results. I have tried the below resolution but still have same issue. Do we need to add authorization in the docker image ?

_Important: If you're using Mac OS and the previous command fails with a Connection refused error, see Connection refused error when running locally. If the previous command fails with a healthapiclient.NewHL7V2Client: oauth2google.DefaultTokenSource: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information. error, see could not find default credentials error when running locally._

     1 mllp_adapter.go:58] failed to connect to HL7v2 API: oauth2google.DefaultTokenSource: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

**Comment by lucasmncastro** [comment]
Up! I'm facing the same.

**Comment by lucasmncastro** [comment]
@cunninghamb505 I was checking the code and I figured out the `credentials` option to set the credentials file.

The docker command should be like:

```
docker run \
    --network=host \
    -v ~/.config:/root/.config \
    gcr.io/cloud-healthcare-containers/mllp-adapter \
    /usr/mllp_adapter/mllp_adapter \
    --hl7_v2_project_id=$PROJECT_ID \
    --hl7_v2_location_id=$LOCATION \
    --hl7_v2_dataset_id=$DATASET_ID \
    --hl7_v2_store_id=$HL7V2_STORE_ID \
    --credentials=/root/.config/$GOOGLE_APPLICATION_CREDENTIALS \
    --export_stats=false \
    --receiver_ip=0.0.0.0 \
    --port=2575 \
    --api_addr_prefix=https://healthcare.googleapis.com:443/v1 \
    --logtostderr

```

Here it worked fine.

**Comment by raycaig** [comment]
@cunninghamb505 The MLLP adapter uses the application default credential by default. You will need to acquire new user credential on the machine where you're running the adapter. To acquire the credential, you can run the following gcloud command: [`gcloud auth application-default login`](https://cloud.google.com/sdk/gcloud/reference/auth/application-default/login). The obtained credentials should be saved to `~/.config/gcloud/application_default_credentials.json` file. And after that you should be able to run the MLLP adapter.

**Comment by lucasmncastro** [comment]
@raycaig thanks a lot!

**Comment by cunninghamb505** [comment]
Yes ! looks like its working now, Thank you
