### ISSUE TITLE
HL7 ingest error message

### ISSUE THREAD

**Issue by lidpee** [GoogleCloudPlatform/mllp#21]
Hi

How can we get the payload data for hl7 ingest error message. Sometimes the care  system get NACK with AE and the error message. How to get that payload to check what is the problem. Below given a sample NACK received by the care system.

MSA|AE|Q2827650752T3305190973|unsupported encoding in message, only ASCII and UTF-8 are supported

Thanks & Regards
Dileep. O

**Comment by paulchurch** [comment]
The API doesn't store payloads of messages it rejects, but you can log them by configuring an intermediate component such as the MLLP adapter or an interface engine to store failed messages in a location of your choice.

The most common cause of "unsupported encoding" is an unexpected line delimiter, as the encoding is typically the last field in the MSH segment and parsing can run into the next segment if the line is not split.
