### ISSUE TITLE
Security Question

### ISSUE THREAD

**Issue by cunninghamb505** [GoogleCloudPlatform/mllp#22]
More of a question for on premise setup. Does this send HL7 via HTTPS to the GCP cloud? Do we need to use a VPN if its already sending via HTTPS? 
Thanks

**Comment by paulchurch** [comment]
Yes, the adapter communicates to GCP over HTTPS. The documentation suggests a VPN primarily for the MLLP side of the connection which is unencrypted.

There could be other network security considerations, for example making sure the adapter does not communicate with anything other than the correct GCP endpoint, but a VPN is not needed for encryption.
