### ISSUE TITLE
Google MLLP adapter doen't back NACK on both invalid file format and invalid message

### ISSUE THREAD

**Issue by knidhin1** [GoogleCloudPlatform/mllp#9]
**_echo -n -e "\x0b$(cat file.txt )\x1c\x0d" | nc xxx.xxx.xxx.xxx 2575_**
No NACK but on kubernete logs

_**kubectl logs -f pod_name**_

o:182] Sending message of size 3042.
E1205 18:41:32.620325       1 mllpreceiver.go:118] handleMessage: Send: request failed: 400
{
  "error": {
    "code": 400,
    "message": "unsupported encoding in message, only ASCII and UTF-8 are supported",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.cloud.healthcare.v1beta1.hl7v2.IngestMessageErrorDetail",
        "hl7Nack": "TVNIfF5+XCZ8fHxFRUh8RUhTfDIwMTkxMjA1MTg0MTMyfHxBQ0t8MTZlMWU1NjUtMmJlOS00ODk1LWEyYTMtZWM0MzJjMGUwMmRkfFB8Mi4zDU1TQXxBRXwxMDI2Mjk1fHVuc3VwcG9ydGVkIGVuY29kaW5nIGluIG1lc3NhZ2UsIG9ubHkgQVNDSUkgYW5kIFVURi04IGFyZSBzdXBwb3J0ZWQ="
      }
    ]
  }
}
I1205 18:41:32.620344       1 mllpreceiver.go:119] Closed connection from 10.8.0.1:62723
I1205 18:41:34.709448       1 mllpreceiver.go:107] Accepted connection from 10.8.0.1:62784
I1205 18:41:35.697632       1 healthapiclient.go:182] Sending message of size 3042.
E1205 18:41:35.756086       1 mllpreceiver.go:118] handleMessage: Send: request failed: 400
{
  "error": {
    "code": 400,
    "message": "unsupported encoding in message, only ASCII and UTF-8 are supported",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.cloud.healthcare.v1beta1.hl7v2.IngestMessageErrorDetail",
        "hl7Nack": "TVNIfF5+XCZ8fHxFRUh8RUhTfDIwMTkxMjA1MTg0MTM1fHxBQ0t8Y2NkZmIxN2YtOGMyZC00Mjg0LTgyMmMtZDQ3N2I0YTk0NWVlfFB8Mi4zDU1TQXxBRXwxMDI2Mjk1fHVuc3VwcG9ydGVkIGVuY29kaW5nIGluIG1lc3NhZ2UsIG9ubHkgQVNDSUkgYW5kIFVURi04IGFyZSBzdXBwb3J0ZWQ="
      }
    ]
  }
}
I1205 18:41:35.756106       1 mllpreceiver.go:119] Closed connection from 10.8.0.1:62784

**Comment by raycaig** [comment]
Please use the latest MLLP adapter image, it should return all NACK messages properly.
